### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by apearson** [apearson/insteon-plm#19]
- [ ] Device Management
- [ ] Device Classes
   - [ ] Dimmable Lighting Control
   - [ ] Switched Lighting Control
   - [ ] Sensors and Actuators
   - [ ] Security, Health, Safety
- [x] Insteon Base Class
  - [x] Base class needs to have a static method for all commands that don't require a link in the db.  This static method will be called from the instance method
- [ ] Base classes
  - [ ] Should make base classes containing all Insteon commands and requirements to execute those commands.  The a higher order class should contain the functions that utilize those commands to do interesting things.  This separates the Insteon domain from the library domain.

**Comment by apearson** [comment]
Device management:
  - Need to develop an understand of how to maintain a device database record in the PLM.  
  - First theory was to have all devices control the PLM, but this failed as the LED bulb and other devices can not act as controllers. 
  - Next theory is to see if the PLM can act as a controller to all devices (remotes included)
    - All devices seem to be able to act as responder to the PLM.
    - The first group on the PLM (one controlled by set button) should be use for device management
    - All devices should be linked as a responder to the PLM to be considered "controlled"

**Comment by apearson** [comment]
Linking and unlinking now work with a bug or two
